name: Bug Report
description: Report a bug in a released version of AgOpenGPS
title: ""
labels: ["needs-triage"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! Please provide as much detail as possible to help us fix it.

  - type: input
    id: version
    attributes:
      label: AgOpenGPS Version
      description: Which version are you using? (Check Menu > About in the application)
      placeholder: "e.g., v6.8.0, v7.0.1, develop[a1b2c3d]..."
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: "e.g., Windows 11, Windows 10, Ubuntu 24.04 with Wine..."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Open AgOpenGPS...
        2. Go to Settings...
        3. Click on...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (crashes, data loss)
        - High (major feature broken)
        - Medium (minor issue)
        - Low (cosmetic)
    validations:
      required: false

  - type: dropdown
    id: hardware
    attributes:
      label: Hardware Setup
      description: What type of hardware setup are you using?
      options:
        - GPS receiver only
        - GPS + Section Control
        - GPS + Auto-steer
        - Full setup (GPS + Section Control + Auto-steer)
        - Simulator (no hardware)
        - Other
    validations:
      required: false

  - type: textarea
    id: hardware_details
    attributes:
      label: Hardware Details (if applicable)
      description: Provide specific details about your hardware components
      placeholder: |
        GPS receiver: (e.g., F9P, BNO085)
        Connection type: (e.g., USB, Ethernet, UDP)
        PCB board: (e.g., v4.1 Standard, v5.0)
        Auto-steer motor: (if using auto-steer)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Any error messages, crash dialogs, or log files
      placeholder: |
        Copy and paste any error messages you see.
        Log files can be found in the AgOpenGPS installation folder.
      render: text
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, videos, field files, configuration files, etc.
      placeholder: |
        Add any other context that might help diagnose the issue.
        If the issue relates to a field, please upload the field folder as a zip file
        found in C:\Users\username\Documents\AgOpenGPS\Fields\
    validations:
      required: false