name: Feature Request
description: Suggest a new feature or enhancement for AgOpenGPS
title: ""
labels: ["needs-triage"]
type: "Feature"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What workflow would it improve?
      placeholder: |
        Example: "When working with small fields, I need to manually adjust the AB line offset multiple times..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work? 
      placeholder: |
        Describe your ideal solution. 
        If this involves UI changes, attach mockups, sketches, or screenshots
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Critical (blocks work)
        - High (would save significant time/effort)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help understand this request
      placeholder: Links to similar features in other software, technical details, etc.
    validations:
      required: false
